### ISSUE TITLE
Failed to load system libaacdecoder.so library on Marshmallow Android version.

### ISSUE THREAD

**Issue by xjurcak** [iammert/RadioPlayerService#13]
Hello, we using your lib to play mp3 streams. We have a problem with loading of native libraries (see stack trace below) on Marshmallow+. Library works fine on older android versions.

>java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/sk.mofa.radio.jemne2/lib/arm/libaacdecoder.so: has text relocations
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                        at java.lang.System.loadLibrary(System.java:1076)
                                                                    at com.spoledge.aacdecoder.Decoder.loadLibrary(Decoder.java:187)
                                                                       at com.spoledge.aacdecoder.Decoder.create(Decoder.java:221)
                                                                         at com.spoledge.aacdecoder.Decoder.create(Decoder.java:198)
                                                                         at com.spoledge.aacdecoder.AACPlayer.createDecoder(AACPlayer.java:508)
                                                                         at com.spoledge.aacdecoder.MultiPlayer.createDecoder(MultiPlayer.java:91)
                                                                         at com.spoledge.aacdecoder.AACPlayer.<init>(AACPlayer.java:130)
                                                                         at com.spoledge.aacdecoder.MultiPlayer.<init>(MultiPlayer.java:81)
                                                                         at co.mobiwise.library.radio.RadioPlayerService.getPlayer(RadioPlayerService.java:385)
                                                                         at co.mobiwise.library.radio.RadioPlayerService.onCreate(RadioPlayerService.java:212)
                                                                         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                                         at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by carmelo-ruota** [comment]
Can anyone help me whit this problem? I can't set targetSdk to 22 instead 23 (as discussed on issue #18 ).

**Comment by Vivekban** [comment]
the compiled files which are compatible for android M
armeabi / libaacdecoder.so
armeabi-v7a / libaacdecoder.so
can be found here
[(https://mega.nz/#!EQIVTLIL!mwwakCztR5yd_VjAjS7TJ0kCKO3hrH5mqFkcth9SLc0)]

for more details look out this thread
[https://github.com/vbartacek/aacdecoder-android/issues/76]

**Comment by JorgeBazarte** [comment]
When I add the .jar and src/* files I get the next error:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/spoledge/aacdecoder/AACPlayer.class

**Comment by ghost** [comment]
How to Solve this issue using https://mega.nz/#!EQIVTLIL!mwwakCztR5yd_VjAjS7TJ0kCKO3hrH5mqFkcth9SLc0

link kindly tell in details

**Comment by Sarun1001** [comment]
@ZulqurnainSDSOL  Please fix the link

**Comment by ghost** [comment]
@Sarun1001  working fine on my side , try changing browser

**Comment by Sarun1001** [comment]
@ZulqurnainSDSOL  Hi buddy, thanks for the reply.
But it's still not working on both chrome and firefox
" An error occurred while loading MEGA.

The file "lang/en_1bb81c5261477a101e5304b9c9b53e3c9863c07896fdd1f8d428a0678c2625c0.json" could not be loaded.

Please try again later. We apologize for the inconvenience.

If the problem persists, please try disabling all third-party browser extensions, update your browser and MEGA browser extension to the latest version and reload the page. If that does not help, contact support@mega.nz

BrowserID: mozilla/5.0 (windows nt 6.3; win64; x64; rv:56.0) gecko/20100101 firefox/56.0"
 this is what i get.
 Can you please post that solution here.

**Comment by ghost** [comment]
I've uploaded on github now , download it 
[acc_decoder_M.zip](https://github.com/iammert/RadioPlayerService/files/1426330/acc_decoder_M.zip)

**Comment by Sarun1001** [comment]
@ZulqurnainSDSOL  Thanks a lot bro

**Comment by scysys** [comment]
> How to Solve this issue using https://mega.nz/#!EQIVTLIL!mwwakCztR5yd_VjAjS7TJ0kCKO3hrH5mqFkcth9SLc0
> 
> link kindly tell in details

What about 64Bit for this changes?
