### ISSUE TITLE
Fatal issue

### ISSUE THREAD

**Issue by ferenczAndras** [iammert/RadioPlayerService#18]
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.ferenczandras.marosvasarhelyiradio-2/lib/arm/libaacdecoder.so: has text relocations
       at java.lang.Runtime.loadLibrary(Runtime.java:372)
       at java.lang.System.loadLibrary(System.java:1076)
       at com.spoledge.aacdecoder.Decoder.loadLibrary(Decoder.java:187) 
       at com.spoledge.aacdecoder.Decoder.create(Decoder.java:221) 
       at com.spoledge.aacdecoder.Decoder.create(Decoder.java:198) 
       at com.spoledge.aacdecoder.AACPlayer.createDecoder(AACPlayer.java:508) 
       at com.spoledge.aacdecoder.MultiPlayer.createDecoder(MultiPlayer.java:91) 
       at com.spoledge.aacdecoder.AACPlayer.<init>(AACPlayer.java:130) 
       at com.spoledge.aacdecoder.MultiPlayer.<init>(MultiPlayer.java:81) 
       at co.mobiwise.library.radio.RadioPlayerService.getPlayer(RadioPlayerService.java:401) 
       at co.mobiwise.library.radio.RadioPlayerService.onCreate(RadioPlayerService.java:228) 
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2895) 
       at android.app.ActivityThread.access$1900(ActivityThread.java:157) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439) 
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5527) 
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
```

It was reported right now by Crashlitycs.. what can be the problem ?

**Comment by nestor-bonilla-s** [comment]
When your app crash? it is when you change the orientation from landscape to portrait or vice versa? if yes, I think I have the same issue and I have not found a solution yet :(

**Comment by iammert** [comment]
It is a library's marsmallow problem. Could not fixed it yet. If you have any solution, PRs are welcome.

**Comment by ferenczAndras** [comment]
I have fixed the orientation to portrait, so something else needs to be the problem...

**Comment by nestor-bonilla-s** [comment]
Thanks your your answer @ferenczAndras , I though this issue was related with mine, and well I experience an issue with the orientation change on my Samsung Galaxy S6 with the Android 5.1.1 version, for clarification I made a video to show where the app crash, if you have any piece of advice to solve this issue it would be great! Thanks. 
Youtube video link: [https://youtu.be/T_xP0fAaOn4](url)

**Comment by rpinto18** [comment]
@iammert @ferenczAndras @nestor-bonilla-s 

I solved it by setting
  `compileSdkVersion 23`
 ` buildToolsVersion "23.0.1"`

but targetSdkVersion   use `targetSdkVersion 22` and also `android: screenOrientation = "portrait"`

I think this solution is not optimal, Greetings.

**Comment by rpinto18** [comment]
Solution error android 6, replace library files.
https://mega.nz/#!EQIVTLIL!mwwakCztR5yd_VjAjS7TJ0kCKO3hrH5mqFkcth9SLc0

I use, and it works.
`   compileSdkVersion 23
    buildToolsVersion "23.0.3"`

` minSdkVersion 14
        targetSdkVersion 23`

**Comment by GrafOrlov** [comment]
@rpinto18 your solution works fine, targetSdkVersion 24, Nexus 6P, android 6.0.1.
@iammert please update files of the library

**Comment by suman-tms** [comment]
hi @GrafOrlov can you tell me how did u solved this problem in detail. I am having the same problem in Marshmallow  but cant fix it
